### PR TITLE
feat: Add parse methods to all score implementations

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**

### CODE REVIEW

**Comment by triceo** [comment]
Is there a reason why we're adding this?

**Comment by Christopher-Chianelli** [comment]
> Is there a reason why we're adding this?

Cause Score classes in Java has `parse` and it is extremely convenient for deserialization from score string?

**Comment by triceo** [comment]
Any chance we could call those Java solver methods under the hood, instead of duplicating the code?

**Review by zepfred — APPROVED** [review]

**Comment by Christopher-Chianelli** [comment]
> Any chance we could call those Java solver methods under the hood, instead of duplicating the code?

No; these are pure Python objects so they can be handled by Python libraries

**Pull request merged**
